

# Common settings for all DBs
common: &COMMON
  encoding: utf8
  pool: 5
  timeout: 5000
  adapter: sqlite3

production:
  <<: *COMMON
  database: db/production.sqlite

development:
  <<: *COMMON
  database: db/development.sqlite

test: &TEST
  <<: *COMMON
  database: db/test.sqlite

cucumber:
  <<: *TEST
